services:
  postgres:
    image: postgres:16
    container_name: gazel_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: gazel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gazel_password
      TZ: America/Costa_Rica
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - gazel_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gazel_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  gazel_network:
    driver: bridge
